Repository jeju-weather/jeju-weather, pull requests merged in 2023-04, with the labels that each got.

#40 관광지역 리스트 UI 구현
  src/components/TourList/TourInfo/index.tsx
  src/components/TourList/index.tsx
  src/components/TourList/style.tsx
  src/const/TourCity.ts
  src/pages/TourCity/index.tsx
  src/pages/TourCity/style.tsx
Labels: UI

#43 Feat: api fetch 커스텀 훅 구현
  src/hooks/useAxios.ts
Labels: enhancement

#45 설계 미스로 에러 발생하여 react-query 패키지로 수정
  package-lock.json
  package.json
  src/App.tsx
  src/apis/index.ts
  src/apis/weather.ts
  src/components/Icons/ClothesIcon/index.tsx
  src/hooks/useAxios.ts
  src/pages/Home/index.tsx
  src/store/modules/index.ts
  src/store/modules/weatherInfo/index.ts
Labels: bugFix, enhancement, refactor

#47 Style: 폰트 변경
  public/index.html
  src/style/global.style.ts
Labels: style

#49 Fix: 기존 구현 페이지 삭제 및 라우터 경로 변경
  src/Router/index.tsx
  src/components/TourList/TourInfo/index.tsx
  src/components/TourList/style.tsx
Labels: enhancement, UI, style

#51 Fix: 사용하지 않는 코드삭제
  src/pages/Home/index.tsx
Labels: bugFix

#54 Refactor: api fetch 방식 변경
  src/apis/hallasan.ts
  src/apis/index.ts
  src/assets/images/hallasan/map.png
  src/pages/Hallasan/index.tsx
  src/react-app-env.d.ts
  src/types/hallasan.ts
Labels: UI, refactor

#55 Docs: git 주소 변경
  README.md
Labels: documentation
